version: '2.1'
#https://github.com/bitnami/bitnami-docker-mysql
#https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y/41854997#41854997
networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: 'bitnami/mysql:latest'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=my_database
    networks:
      - app-tier
    ports:
      - "3306:3306"
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 5s
      timeout: 5s
      retries: 6
  my_login_service:
    image: 'login:2.5.4'
    environment:
      - RDS_HOSTNAME=mysql://mysql:3306/my_database
      - RDS_USERNAME=root
      - RDS_PASSWORD=password123
      - SERVER_PORT=8080
    networks:
      - app-tier
    ports:
      - "8080:8080"
    expose:
      - 3306
    depends_on:
      mysql:
        condition: service_healthy
  my_book_service:
    image: 'book:2.5.4'
    environment:
      - RDS_HOSTNAME=mysql://mysql:3306/my_database
      - RDS_USERNAME=root
      - RDS_PASSWORD=password123
      - SERVER_PORT=8081
    networks:
      - app-tier
    ports:
      - "8081:8081"
    expose:
      - 3306
    depends_on:
      mysql:
        condition: service_healthy
#  my_order_service:
#    image: 'order:2.5.4'
#    environment:
#      - RDS_HOSTNAME=mysql://mysql:3306/my_database
#      - RDS_USERNAME=root
#      - RDS_PASSWORD=password123
#      - SERVER_PORT=8082
#    networks:
#      - app-tier
#    ports:
#      - "8082:8082"
#    expose:
#      - 3306
#    depends_on:
#      mysql:
#        condition: service_healthy

volumes:
  mysql_data:
    driver: local