spring:
  datasource:
    url: jdbc:h2:file:~/SEP_login_db;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
#    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
#  sql:
#    init:
#      mode: always
server:
  error:
    include-stacktrace: always
  port: 8080
  error:
#    set this to never in production
    include-stacktrace: on_param