spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cvf1hibyktqg.ap-southeast-2.rds.amazonaws.com:3306/development_database
    username: admin
    password: nagArijS6HtusuJ
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
server:
  error:
    include-stacktrace: always
  port: 8080