INSERT INTO USER (ID, ABN, CREATE_AT, FULL_NAME, PASSWORD, UPDATE_AT, USERNAME) VALUES
    (1, NULL, NULL, 'admin', 'admin', NULL, 'admin');

INSERT INTO USER_AUTHORITIES (USER_ID, AUTHORITIES) VALUES
    (1, 'ADMIN');